import Head from 'next/head';
import { Inter } from '@next/font/google';
import TabGroup from '../components/Tabs';
import ImgService from '../services/imgService';

import Journal from './Journal';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ mappedPhoto }) {
  return (
    <div className="h-full ">
      <Head>
        <title>SENORITA PHOTOGRAPHY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" md:pt-[30px] ">
        <Journal />
        <TabGroup photos={mappedPhoto} key="Photo-1" />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const imgService = new ImgService();
  const photos = await imgService.getCachePhotos();

  return {
    props: {
      mappedPhoto: photos,
    },
  };
}
